name: Build JAR on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # Matches the enforced version in the POM
    - name: Update POM version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Updating POM version to $TAG_NAME"
        mvn versions:set -DnewVersion=$TAG_NAME
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTest

    - name: Rename JAR
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        JAR_NAME="python-generator-$TAG_NAME.jar"
        mv target/python-generator-*.jar target/$JAR_NAME

    - name: Revert POM changes
      run: git checkout -- pom.xml

    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: target/*.jar
